#import "/utils/todo.typ": TODO

= Related Work
#TODO[
  Describe related work regarding your topic and emphasize your (scientific) contribution in contrast to existing approaches / concepts / workflows. Related work is usually current research by others and you defend yourself against the statement: “Why is your thesis relevant? The problem was al- ready solved by XYZ.” If you have multiple related works, use subsections to separate them.
]

Current research on LLM-supported educational workflows shows a consistent pattern: models reduce manual effort, but reliable use still requires explicit human review. Grading-focused studies demonstrate this clearly. Xu et al. combine ChatGPT-4o grading with a human revision step #cite(<Xu2025469>), and Cisneros-González et al. report a JorGPT workflow in which instructors choose both model and rubric #cite(<Cisneros-Gonzalez2025>). Bernik et al. report close agreement between AI and teacher grades overall, with stricter AI grading in specific submissions #cite(<Bernik2025>).

Design-focused studies support the same conclusion. Work on formative coding assessment and design-pattern analysis keeps educators in control of final judgments #cite(<Knipp2025379>) #cite(<Dosaru2025>). Similar findings appear outside programming: Funayama et al. route low-confidence cases to humans #cite(<Funayama2022465>), and Emirtekin et al. report lower AI-human agreement for tasks that require deeper reasoning #cite(<Emirtekin2026>). These studies show that hybrid AI-human grading can improve quality and reduce workload when workflows enforce human decisions.

A second group of studies addresses authoring of questions, exams, and related teaching material. LLMs scale drafting, but educator moderation remains necessary for pedagogical quality. Kituku et al. report year-long classroom use of generative AI (GenAI) questions with instructor moderation #cite(<Kituku2025>). Cheng et al. present TreeQuestion as a teacher-in-the-loop multiple-choice question (MCQ) authoring workflow #cite(<Cheng2024>). Cui et al. generate large candidate sets and rely on expert review for quality selection #cite(<Cui20251094>). Tyndall et al. and Nyaaba et al. show that retrieval and interactive prompting improve outcomes when teachers review final material #cite(<Tyndall2025>) #cite(<Nyaaba2025>).

Instructor-facing support systems extend beyond grading and authoring into daily teaching workflows. Wolff et al. present EDUHints, where AI proposes hints and instructors approve what students receive #cite(<Wolff2025897>). In Artemis, Iris already provides student-facing AI tutoring, which creates a strong baseline for extending assistance toward instructor and editor tasks #cite(<Bassner2024394>). Frameworks by Tan et al. and Tebourbi et al. emphasize structured generation workflows, explicit evaluation, and human validation #cite(<Tan2025>) #cite(<Tebourbi2025>).

Some studies primarily inform governance constraints. Su et al. focus on detecting AI-generated student submissions in an intelligence-augmentation setup with human oversight #cite(<Su20251036>). This work does not solve exercise-review workflows directly, but it clarifies operational requirements such as accountability and reliability.

The literature currently emphasizes grading support and content generation, but only a few papers cover the full programming-exercise authoring lifecycle. Research rarely connects AI issue detection, human discussion, concrete edits, and traceable decision history in one workflow. This thesis addresses that gap by integrating consistency-check findings into a persistent review process that keeps decisions traceable and final changes under explicit human control.
