#import "/utils/todo.typ": TODO

= Related Work
#TODO[
  Describe related work regarding your topic and emphasize your (scientific) contribution in contrast to existing approaches / concepts / workflows. Related work is usually current research by others and you defend yourself against the statement: “Why is your thesis relevant? The problem was al- ready solved by XYZ.” If you have multiple related works, use subsections to separate them.
]

To position this thesis, it is useful to look at current work on LLM-supported educational workflows and identify where clear gaps remain. A consistent pattern in grading-related papers is that models can reduce manual effort, but reliable use still depends on explicit human review. For example, Xu et al. combine ChatGPT-4o grading with a human step that revises the generated feedback #cite(<Xu2025469>), while Cisneros-González et al. report a workflow in JorGPT where instructors choose both the model and the grading rubric #cite(<Cisneros-Gonzalez2025>). Bernik et al. report that AI grades were generally close to teacher grades, but in some submissions the AI graded more strictly #cite(<Bernik2025>). This is reinforced by design-focused work on formative coding assessment #cite(<Knipp2025379>) and design-pattern analysis, both of which keep educators in control of final judgments #cite(<Dosaru2025>). Even outside programming, the pattern is similar: Funayama et al. route low-confidence cases to humans #cite(<Funayama2022465>), and Emirtekin et al. show lower AI-human agreement for tasks that require deeper reasoning #cite(<Emirtekin2026>). Taken together, this strand gives a strong picture of how hybrid AI-human grading can improve quality and reduce workload.

Another group of studies looks at creating assessment material (for example, questions and exams) and related teaching content. Here, LLMs can scale authoring significantly, yet moderation remains necessary for pedagogical quality. Kituku et al. report a year-long classroom use of GenAI-generated questions with instructor moderation #cite(<Kituku2025>), and Cheng et al. present TreeQuestion as a teacher-in-the-loop MCQ authoring workflow #cite(<Cheng2024>). In a similar direction, Cui et al. generate a large pool of candidate questions and then use expert review to keep high-quality items and remove weak ones #cite(<Cui20251094>). Tyndall et al. show that exam generation improves when the model is given retrieved course material as context, instead of relying only on its pretrained knowledge #cite(<Tyndall2025>), while Nyaaba et al. show that interactive prompting plus teacher revision improves culturally responsive lesson planning #cite(<Nyaaba2025>). Overall, this line of work shows that LLMs are effective drafting tools when teacher moderation is built into the process.

Related work on instructor-facing support systems extends beyond grading and authoring into daily teaching workflows. Wolff et al. demonstrate this with EDUHints, where AI proposes hints but instructors approve what students receive #cite(<Wolff2025897>). In Artemis, Iris already provides student-facing AI tutoring, which is important context for extending assistance toward instructor/editor tasks #cite(<Bassner2024394>). More general frameworks by Tan et al. #cite(<Tan2025>) and Tebourbi et al. #cite(<Tebourbi2025>) emphasize structured generation workflows, explicit evaluation, and human validation. In short, this strand highlights practical design principles for trustworthy instructor-facing AI support.

Some work is mainly relevant as governance context rather than direct assessment or authoring support. Su et al., for instance, focus on detecting AI-generated student submissions and deploy this in an intelligence-augmentation setup with human oversight #cite(<Su20251036>). This does not directly solve exercise-review workflows, but it is useful for framing deployment constraints such as accountability and operational reliability.

Overall, the literature currently forms a clear progression: most work focuses on grading support, and a second group focuses on creating questions or other teaching material. However, only few papers cover the full programming-exercise creation process from start to finish. In particular, there is little work on workflows that connect AI issue detection, human discussion, concrete edits, and traceable decision history in one place. This thesis targets that gap by integrating consistency-check findings into a persistent review process, so issues can be discussed in context, decisions remain traceable, and final changes stay under explicit human control.
